language: php

php:
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: 7
        - php: nightly

sudo: false

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - php artisan key:generate

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./bin/test-reporter