language: php

php:
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit