language: php
dist: trusty

php:
  - 7.1
  - 7.2
  - nightly

matrix:
    allow_failures:
        - php: nightly

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - travis_retry composer install --prefer-dist --no-interaction
  - php artisan key:generate --force
  - php artisan config:clear

script: phpunit