language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

services:
    - mysql
    - redis-server

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - mysql -e 'create database screeenly_test;'
  - php artisan migrate

script: phpunit